#!/bin/bash

# see https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

# $IMAGE_NAME var is injected into the build so the tag is correct.
docker build --build-arg VCS_REF=`git rev-parse — short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  -t $IMAGE_NAME .
